sudo: false
language: python
# cache package wheels (1 cache per python version)
cache: pip
python:
  - "3.3"
  - "3.4"
  # Specifically request 3.5.1 because we need to be compatible with that.
  - "3.5.1"
  - "3.6"
  - "3.7-dev"
  # Pypy build is disabled because it doubles the travis build time, and it rarely fails
  # unless one one of the other builds fails.
  # - "pypy3"

install:
  - pip install -r test-requirements.txt
  - python setup.py install

script:
  - python runtests.py -x lint
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then flake8; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]] && [[ "$(git diff --name-only $TRAVIS_COMMIT_RANGE | grep -v -e 'docs/' -e 'md$' -e 'rst$')" != "" ]]; then pip install -q -r requirements-docs.txt; SPHINX_OPTS="-nW" make html; fi
